import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import io from 'socket.io-client'
import { Socket } from 'socket.io-client'
let socket: Socket;

export default function Home() {
  const [input, setInput] = useState('')

  const socketInitializer = async () => {
    await fetch('/api/socket');
    socket = io()

    socket.on('connect', () => {
      console.log('connected')
    })

    socket.on('update', msg => {
      console.log(msg)
      setInput(msg)
    })
  }

  const onChangeHandler = (e: any) => {
    socket?.emit('input-change', e.target.value)
  }

  useEffect(() => {
    socketInitializer()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Transaction App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

       
      </main>

      <input onChange={onChangeHandler} value={input} />

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
